using Android.Content;
using Android.Service.QuickSettings;
using VpnHood.AppLib.App.Android.Constants;
using VpnHood.AppUi.Hosting.Avalonia.Android;
using VpnHood.AppUi.Presentation.Classic.Avalonia;

namespace VpnApp.Android.Google;

// The launcher and the UI in one activity: Avalonia's, in the theme that UI brings. The app takes no
// access key from outside, so it takes no intent that carries one.
[Activity(
    // Launchers keep the app's home-screen icon by this Java name. Stated, since the one generated by
    // default follows the project's name and would move with a rename.
    Name = "app.MainActivity",
    MainLauncher = true,
    Label = AppConstants.AppName,
    Theme = "@style/Theme.VpnHood.Avalonia",
    LaunchMode = AndroidMainActivityConstants.LaunchMode,
    Exported = AndroidMainActivityConstants.Exported,
    WindowSoftInputMode = AndroidMainActivityConstants.WindowSoftInputMode,
    ScreenOrientation = AndroidMainActivityConstants.ScreenOrientation,
    ConfigurationChanges = AndroidMainActivityConstants.ConfigChanges)]
[IntentFilter([Intent.ActionMain], Categories = [Intent.CategoryLauncher, Intent.CategoryLeanbackLauncher])]
[IntentFilter([TileService.ActionQsTilePreferences])]
public class MainActivity : AndroidAvaloniaMainActivity<ClassicAvaloniaApp>;
